- hosts: all
  pre_tasks:
  - name: pre tasks
    import_tasks: tasks/pre_tasks.yml

- hosts: fedora
  roles:
  - linux/base

- hosts: workstations_fedora
  roles:
  - linux/personal
  - linux/remote-workstation

- hosts: all
  post_tasks:
  - name: pre tasks
    import_tasks: tasks/post_tasks.yml
