- hosts: all
  pre_tasks:
  - name: pre tasks
    import_tasks: tasks/pre_tasks.yml

- hosts: all
  roles:
  - base

- hosts: workstations
  roles:
  - workstation

- hosts: all
  post_tasks:
  - name: pre tasks
    import_tasks: tasks/post_tasks.yml
