- include_tasks: software/repositories_{{ ansible_distribution|lower }}.yml
- import_tasks: software/repositories_flatpak.yml

- import_tasks: hardware/amd_gpu.yml
- import_tasks: hardware/intel_hd_audio.yml

- import_tasks: software/utilities.yml
- import_tasks: software/audio.yml
- import_tasks: software/bloatware.yml
- import_tasks: software/remmina.yml
- import_tasks: software/vpn.yml
