- name: Enable the RPM Fusion repository
  become: true
  dnf:
    state: present
    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
  when: ansible_distribution == 'Fedora'

- name: List enabled dnf repositories
  become: true
  command: dnf repolist enabled
  register: _
  changed_when: false
  when: ansible_distribution == 'Fedora'

- name: Check if rpmfusion-nonfree-steam enabled
  set_fact:
    rpmfusion_nonfree_steam_enabled: "{{ 'rpmfusion-nonfree-steam' in _.stdout }}"
  when: ansible_distribution == 'Fedora'

- name: Enable rpmfusion-nonfree-steam
  become: true
  command: dnf config-manager --enable rpmfusion-nonfree-steam
  warn: false
  when: rpmfusion_nonfree_steam_enabled is defined and not rpmfusion_nonfree_steam_enabled

- name: Add flathub (required for Spotify)
  become: true
  flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: Install GUI utilities
  become: true
  package:
    state: latest
    name:
    - gimp
    - keepassxc
    - telegram-desktop  # requires RPM Fusion
    - transmission
    - vlc  # requires RPM Fusion

- name: Uninstall bloatware
  become: true
  package:
    state: absent
    name:
    - cheese
    - orca
    - rhythmbox

- import_tasks: hardware/intel_hda_sound.yml
- import_tasks: software/audio.yml
- import_tasks: software/remmina.yml
