- import_tasks: software/repositories.yml

- import_tasks: hardware/intel_hda_sound.yml

- import_tasks: software/utilities.yml
- import_tasks: software/audio.yml
- import_tasks: software/bloatware.yml
- import_tasks: software/remmina.yml
