- name: Install sound related packages
  become: true
  dnf:
    state: latest
    name:
    - pavucontrol  # Pulse Audio volume control

- name: Uninstall system-wide Spotify
  become: true
  flatpak: name=com.spotify.Client state=absent

- name: Install Spotify
  flatpak: name=com.spotify.Client method=user
