- name: Install sound related packages
  become: true
  package:
    state: latest
    name:
    - pavucontrol  # Pulse Audio volume control

- name: Disable buggy Pipewire
  systemd:
    name: "{{ item }}"
    masked: true
    enabled: false
    state: stopped
    scope: user
  with_items:
  - pipewire.service
  - pipewire.socket

- name: Uninstall system-wide Spotify
  become: true
  flatpak: name=com.spotify.Client state=absent

- name: Install Spotify
  flatpak: name=com.spotify.Client method=user
