- name: Add 3rd party repositories
  become: true
  dnf:
    state: present
    name: fedora-workstation-repositories

- name: Enable the RPM Fusion repository
  become: true
  dnf:
    state: present
    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"

- name: List enabled dnf repositories
  block:
  - become: true
    command:
      cmd: dnf repolist enabled
      warn: false
    register: _
    changed_when: false
  - set_fact:
      dnf_repolist_enabled_stdout: "{{ _.stdout }}"

- name: Enable 3rd party repositories
  become: true
  command:
    cmd: "dnf config-manager --enable {{ item }}"
    warn: false
  when: item not in dnf_repolist_enabled_stdout
  with_items:
  - rpmfusion-nonfree-steam
  - google-chrome
