- name: Add 3rd party repositories
  become: true
  dnf:
    state: present
    name: fedora-workstation-repositories
  when: ansible_distribution == 'Fedora'

- name: Enable the RPM Fusion repository
  become: true
  dnf:
    state: present
    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
  when: ansible_distribution == 'Fedora'

- name: List enabled dnf repositories (1/2)
  become: true
  command:
    cmd: dnf repolist enabled
    warn: false
  register: _
  changed_when: false
  when: ansible_distribution == 'Fedora'
- name: List enabled dnf repositories (2/2)
  set_fact:
    dnf_repolist_enabled_stdout: "{{ _.stdout }}"
  when: ansible_distribution == 'Fedora'

- name: Enable 3rd party repositories
  become: true
  command:
    cmd: "dnf config-manager --enable {{ item }}"
    warn: false
  when: ansible_distribution == 'Fedora' and item not in dnf_repolist_enabled_stdout
  with_items:
  - rpmfusion-nonfree-steam
  - google-chrome

- name: Add flathub (required for Spotify)
  become: true
  flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
