- name: Install eToken dependencies
  become: true
  dnf:
    state: latest
    name:
    - nss-tools
    - pcsc-lite
    - gnutls-utils
    - openssl

- name: Uninstall opensc (makes Firefox non-responsive)
  become: true
  dnf:
    state: absent
    name:
    - opensc

- name: Install openconnect
  become: true
  dnf:
    state: latest
    name:
    - openconnect
    - vpnc-script
    - NetworkManager-openconnect-gnome
