---
# tasks file for roles/linux/personal

- name: Enable the RPM Fusion repository
  become: true
  dnf:
    state: present
    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
  when: ansible_distribution == 'Fedora'

- name: Install personal software
  become: true
  package:
    state: latest
    name:
    - telegram-desktop  # requires RPM Fusion
    - vlc  # requires RPM Fusion
    - transmission
    - gimp

- name: Install sound related packages
  become: true
  package:
    state: latest
    name:
    - pavucontrol  # Pulse Audio volume control

- name: Disable buggy Pipewire
  systemd:
    name: "{{ item }}"
    masked: true
    enabled: false
    state: stopped
    scope: user
  with_items:
  - pipewire.service
  - pipewire.socket

- name: Check if Intel HDA sound card is active
  stat: {path: /sys/module/snd_hda_intel}
  register: snd_hda_intel

- name: Disable power saving mode in Intel HDA sound card
  become: true
  copy:
    content: "0\n"
    dest: /sys/module/snd_hda_intel/parameters/power_save
    unsafe_writes: true
  when: snd_hda_intel.stat.isdir is defined and snd_hda_intel.stat.isdir

- name: Disable power saving mode in Intel HDA sound card
  become: true
  lineinfile:
    path: /etc/modprobe.d/sound.conf
    regexp: "^options snd-hda-intel"
    line: options snd-hda-intel power_save=0
    state: present
    create: true
  when: snd_hda_intel.stat.isdir is defined and snd_hda_intel.stat.isdir
