---
# tasks file for roles/linux/remote-workstation

- name: Remove Remmina flatpak
  become: true
  flatpak:
    name: org.remmina.Remmina
    state: absent

- name: Remove Remmina user flatpak
  flatpak:
    name: org.remmina.Remmina
    method: user
    state: absent

- name: Install Remmina
  become: true
  package:
    state: latest
    name:
    - remmina
