dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
- name: fedora33
  box: generic/fedora33
  memory: 1024  # flatpak cannot install Spotify on 512M
  cpus: 2
provisioner:
  name: ansible
  connection_options:
    ansible_connection: ssh
verifier:
  name: ansible
  connection_options:
    ansible_connection: ssh
