dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
- name: fedora33
  box: generic/fedora33
  memory: 1024  # flatpak cannot install Spotify on 512M
  cpus: 2
  groups:
  - workstations
provisioner:
  name: ansible
verifier:
  name: ansible
