- name: Check if AMD GPU is present
  block:
  - name: Check if AMD GPU is present | List VGA devices
    shell: lspci | grep VGA
    register: _
    changed_when: false
  - name: Check if AMD GPU is present | Check
    set_fact:
      has_amd_gpu: "{{ 'AMD' in _.stdout }}"

- name: Configure AMD GPU
  when: has_amd_gpu
  become: true
  block:
  - name: Install AMD GPU fan controller
    pip: name=git+https://github.com/sekogan/amdgpu-fan.git state=latest

  - name: Copy amdgpu-fan configuration
    copy: src=amdgpu-fan/amdgpu-fan.yml dest=/etc/ mode=644
    register: _copy_configuration

  - name: Install amdgpu-fan systemd unit file
    copy: src=amdgpu-fan/amdgpu-fan.service dest=/etc/systemd/system/ mode=644

  - name: Start amdgpu-fan
    systemd: name=amdgpu-fan state=started enabled=yes daemon_reload=yes
    register: _start_service

  - name: Restart amdgpu-fan
    systemd: name=amdgpu-fan state=restarted
    when: _copy_configuration.changed and not _start_service.changed
