- name: Check if Intel HD sound card is present
  block:
  - name: Check if Intel HD sound card is present | List audio devices
    shell: lspci | grep Audio
    register: _
    changed_when: false
  - name: Check if Intel HD sound card is present | Check
    set_fact:
      has_intel_hd_sound: "{{ 'Intel' in _.stdout and 'HD Audio Controller' in _.stdout }}"

- name: Configure Intel HD sound card
  when: has_intel_hd_sound
  become: true
  block:
  - name: Disable power saving mode in Intel HD sound card
    copy:
      content: "0\n"
      dest: /sys/module/snd_hda_intel/parameters/power_save
      mode: 0644
      unsafe_writes: true

  - name: Disable power saving mode in Intel HD sound card
    lineinfile:
      path: /etc/modprobe.d/sound.conf
      regexp: "^options snd-hda-intel"
      line: options snd-hda-intel power_save=0
      state: present
      create: true
      mode: 0644
