- name: Check if Intel HDA sound card is active (1/2)
  stat: path=/sys/module/snd_hda_intel
  register: _
- name: Check if Intel HDA sound card is active (2/2)
  set_fact:
    has_intel_hda_sound: "{{ _.stat.isdir }}"

- name: Disable power saving mode in Intel HDA sound card
  become: true
  copy:
    content: "0\n"
    dest: /sys/module/snd_hda_intel/parameters/power_save
    unsafe_writes: true
  when: has_intel_hda_sound

- name: Disable power saving mode in Intel HDA sound card
  become: true
  lineinfile:
    path: /etc/modprobe.d/sound.conf
    regexp: "^options snd-hda-intel"
    line: options snd-hda-intel power_save=0
    state: present
    create: true
  when: has_intel_hda_sound
