- name: Check if Intel HDA sound card is active
  block:
  - stat: path=/sys/module/snd_hda_intel
    register: _
  - set_fact:
      has_intel_hda_sound: "{{ _.stat.isdir }}"

- name: Configure Intel HDA sound card
  when: has_intel_hda_sound
  become: true
  block:
  - name: Disable power saving mode in Intel HDA sound card
    copy:
      content: "0\n"
      dest: /sys/module/snd_hda_intel/parameters/power_save
      mode: 0644
      unsafe_writes: true

  - name: Disable power saving mode in Intel HDA sound card
    lineinfile:
      path: /etc/modprobe.d/sound.conf
      regexp: "^options snd-hda-intel"
      line: options snd-hda-intel power_save=0
      state: present
      create: true
      mode: 0644
