- name: Install system diagnostic tools
  become: true
  dnf:
    state: latest
    name:
    - htop
    - iotop
    - neofetch
    - net-tools
    - qdirstat
    - strace
    - stress  # stress test for hardware (also see s-tui)
    - sysstat

- name: Install system diagnostic tools via pip
  become: true
  pip:
    state: latest
    name:
    - s-tui  # UI for stress (and load/temp monitor)

- name: Install system administrator utilities
  become: true
  dnf:
    state: latest
    name:
    - curl
    - mc
    - ripgrep
    - tmux
    - vim
    - wget
