---
# tasks file for roles/linux/base

- name: Set host name
  become: true
  hostname:
    name: "{{ inventory_hostname }}"

- name: Install diagnostic tools
  become: true
  package:
    state: latest
    name:
    - htop
    - iotop
    - neofetch
    - net-tools
    - qdirstat
    - strace
    - stress  # stress test for hardware (also see s-tui)
    - sysstat

- name: Install diagnostic tools via pip
  become: true
  pip:
    state: latest
    name:
    - s-tui  # UI for stress (and load/temp monitor)

- name: Install utilities
  become: true
  package:
    state: latest
    name:
    - curl
    - mc
    - ripgrep
    - tmux
    - vim
    - wget

- name: Uninstall bloatware
  become: true
  package:
    state: absent
    name:
    - cheese
    - orca
    - rhythmbox
