name: CI

on:
- push

jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install yamllint
    - name: YAML Lint
      run: |
        yamllint .

  ansible-syntax-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install ansible==2.9.*
    - name: Syntax check
      run: |
        ansible-playbook --syntax-check local.yml

  ansible-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install ansible-lint
    - name: Ansible Lint
      run: |
        ansible-lint -v *.yml

  # Disabled because of https://github.com/ansible/ansible-lint-action/issues/41
  # ansible-lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: ansible/ansible-lint-action@master
  #     with:
  #       targets: |
  #         local.yml
  #       override-deps: |
  #         ansible==2.9
